---
key: "products-1.0.0"
name : "products"
displayName : "products"
description: "Sample API"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/products"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
apiId : "null"
