openapi: 3.0.1
info:
  title: users
  description: API Definition of users
  version: 1.0.0
servers:
- url: http://localhost:8290/users
paths:
  /:
    get:
      responses:
        default:
          description: Default response
